collections:
  - plans
  - projects
defaults:
  - scope:
      path: ''
    values:
      layout: default
livereload: true
permalink: /:basename/
sass:
  sass_dir:  assets/styles
  sourcemap: never
  style:     expanded
theme: null
timezone: America/New_York
