collections:
  - plans
  - projects
defaults:
  - scope:
      path: ''
    values:
      layout: default
livereload: true
permalink: /:basename/
sass:
  implementation: sass-embedded
  sass_dir: assets/styles
theme: null
timezone: America/New_York
